FROM maven:latest

# Copy the code to the image
WORKDIR app
ADD src .
ADD ./pom.xml .

# Generate the artifact
RUN mvn clean package -DskipTests

# EDIT THIS
# Runtime config
EXPOSE 50009

# EDIT THIS
CMD ["mvn", "xxxx"]
