FROM java:8-jre-alpine
COPY target/vdc-repository-engine-0.0.1-SNAPSHOT.jar /app/vdc-repository-engine-0.0.1-SNAPSHOT.jar
COPY etc/configuration.yml /app/configuration.yml
COPY etc/security.yml /app/security.yml
COPY entrypoint.sh /entrypoint.sh
EXPOSE 8080
ENTRYPOINT ["chmod +x /entrypoint.sh"]
