swagger: '2.0'
info:
  title: VDC Blueprint Repository Engine
  version: 0.0.1
paths:
  /blueprints:
    get:
      description: Blueprints Retrieval
      parameters:
        - name: section
          in: query
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
        - name: filter
          in: query
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              _embedded:
                type: array
                items:
                  type: object
              _returned:
                type: integer
    post:
      description: Blueprint Creation
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: blueprint
          in: body
          description: Abstract VDC Blueprint to be stored in the VDC Blueprint Repository
          required: true
          schema:
            type: object
            example:
              INTERNAL_STRUCTURE:
                Overview:
                  name: Jenkins_Dredd
                  description: only for testing
                  tags:
                    - method_id: getPatientBiographicalData
                      tags:
                        - OSR
                        - patient
                        - hospital
                        - biographical
                        - profile
                Data_Sources:
                  - id: patientBiographicalData
                    description: >-
                      Relational database containing biographical data for the
                      hospital patients
                    class: relational database
                    type: MySQL
                Flow:
                  platform: Spark
                Testing_Output_Data:
                  - method_id: getPatientBiographicalData
                    zip_data: 'http://localhost:8080'
              DATA_MANAGEMENT: []
              ABSTRACT_PROPERTIES: []
              COOKBOOK_APPENDIX:
                infrastructure: []
                name: ''
              EXPOSED_API:
                openapi: 3.0.1
                info:
                  title: CAF API
                  version: 0.0.1
                paths:
                  '/patient/{SSN}':
                    get:
                      summary: Get patient's biographical data
                      description: >-
                        This method returns the biographical data for the
                        specified patient (identified via SSN), to be used by
                        medical doctors
                      operationId: getPatientBiographicalData
                      parameters:
                        - name: SSN
                          in: path
                          description: SSN of the patient
                          required: true
                          schema:
                            type: string
                      responses:
                        '200':
                          description: Biographical data of the patient
                          content:
                            application/json:
                              schema:
                                type: object
                      x-data-sources:
                        - patientBiographicalData
      responses:
        '201':
          description: successful operation
          schema:
            type: object
            properties:
              blueprint_id:
                type: array
                items:
                  type: string
            required:
              - blueprint_id
      security:
        - basicAuth: []
  '/blueprints/{blueprint_id}':
    get:
      description: Blueprint Retrieval by id
      produces:
        - application/json
      parameters:
        - name: blueprint_id
          in: path
          required: true
          type: string
          x-example: 5c49caf3763d081d264b2637
        - name: section
          in: query
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        '200':
          description: successful operation
          schema:
            type: object
    patch:
      description: Blueprint Update by id
      consumes:
        - application/json
      parameters:
        - name: blueprint_id
          in: path
          required: true
          type: string
          x-example: 5c49caf3763d081d264b2637
        - name: FieldsToBeUpdated
          in: body
          description: all the fields to be updated
          required: true
          schema:
            type: object
            example:
              INTERNAL_STRUCTURE.Overview.name: new_name
      responses:
        '200':
          description: successful operation
      security:
        - basicAuth: []
    delete:
      description: Blueprint Deletion by id
      parameters:
        - name: blueprint_id
          in: path
          required: true
          type: string
          x-example: 5c49caf3763d081d264b2637
      responses:
        '204':
          description: successful operation
      security:
        - basicAuth: []
securityDefinitions:
  basicAuth:
    type: basic
