swagger: '2.0'
info:
  title: VDC Blueprint Repository Engine
  version: 0.0.1
paths:
  /blueprints:
    get:
      description: Blueprints Retrieval
      parameters:
        - name: section
          in: query
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
        - name: filter
          in: query
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              _embedded:
                type: array
                items:
                  type: object
              _returned:
                type: integer
    
